FROM golang:1.19-alpine as builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /out/app ./api

FROM alpine:latest
WORKDIR /api
COPY --from=builder /out/app /api/app
COPY ./config/. /api/.
COPY ./config/. /api/config/.
EXPOSE 8001 9001
ENTRYPOINT ["/api/app"]